// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace VillaProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240517222202_InitSecondUpdate")]
    partial class InitSecondUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VillaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 5, 18, 1, 22, 1, 534, DateTimeKind.Local).AddTicks(8267),
                            Description = "VillaNameOne and 4 rooms and bathroom",
                            ImageUrl = "Https://placeholder.com",
                            Occupancy = 4,
                            Price = 19000.50m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaName = "VillaNameOne"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 5, 18, 1, 22, 1, 534, DateTimeKind.Local).AddTicks(8317),
                            Description = "VillaNameTwo and 1 rooms",
                            ImageUrl = "Https://placeholder.com",
                            Occupancy = 1,
                            Price = 2500.50m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaName = "VillaNameTwo"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 5, 18, 1, 22, 1, 534, DateTimeKind.Local).AddTicks(8323),
                            Description = "VillaNameThree and 2 rooms",
                            ImageUrl = "Https://placeholder.com",
                            Occupancy = 2,
                            Price = 5000.57m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaName = "VillaNameTwo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
